/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bankUI.components.manager;

import bankBackend.Config;
import bankUI.utils.AlertUI;

import java.lang.reflect.Field;

/**
 * @author NathanY
 */
public class ConfigMgr extends javax.swing.JPanel {

    /**
     * Creates new form ConfigMgr
     */
    public ConfigMgr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        keyF = new javax.swing.JTextField();
        valueF = new javax.swing.JTextField();
        goBtn = new javax.swing.JButton();

        jLabel1.setText("key");

        jLabel2.setText("value");

        keyF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyFActionPerformed(evt);
            }
        });

        goBtn.setText("ok");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(keyF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(valueF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(keyF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(valueF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(goBtn))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        if (valueF.getText().isEmpty()) {
            // query mode
            try {
                Object o = Config.class.getField(keyF.getText()).get(null);
                valueF.setText(o.toString());
            } catch (NoSuchFieldException | IllegalAccessException e) {
                AlertUI.error("No such field:" + e.getMessage());
                return;
            }
            return;
        }
        try {
            Field f = Config.class.getField(keyF.getText());
            if (f.getType().toString().contains("String")) {
                f.set(null, valueF.getText());
            } else if (f.getType().toString().contains("int")) {
                f.set(null, Integer.parseInt(valueF.getText()));
            } else {
                AlertUI.error("Unsupported type:" + f.getType());
                return;
            }
            AlertUI.success("Set successfully:" + String.format("key %s is now %s", keyF.getText(), valueF.getText()));
        } catch (Exception e) {
            e.printStackTrace();
            AlertUI.error(e.getMessage());
        }
    }//GEN-LAST:event_goBtnActionPerformed

    private void keyFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField keyF;
    private javax.swing.JTextField valueF;
    // End of variables declaration//GEN-END:variables
}
