/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankUI.components.home;

import Utils.Logger;
import Utils.Result;
import bankBackend.entity.Report;
import bankBackend.entity.User;
import bankBackend.service.SvcMgr;
import bankUI.utils.AlertUI;

import javax.swing.*;

/**
 * @author NathanY
 */
public class TxnReport extends javax.swing.JFrame {

    private User user;
    private DefaultListModel<String> txnListModel;
    private DefaultComboBoxModel timeSelectModel = new DefaultComboBoxModel<>(new String[]{"day", "week", "month"});
    private int[] epochs = new int[]{24, 24 * 7, 24 * 30};
    private String header = "From\tTo\tType\tValue\tEpoch\tDescription\tCurrencyType";

    /**
     * Creates new form TxnReport
     */
    public TxnReport() {
        this.user = SvcMgr.getSessionService().getSession().unwrap().getUser();
        this.txnListModel = new DefaultListModel<>();
        txnListModel.addElement(header);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        javax.swing.JComboBox<String> timeSelection = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txnList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("View Txn report of user");

        usernameField.setText(this.user.getName());

        jLabel3.setText("in the past");

        timeSelection.setModel(timeSelectModel);

        goButton.setText("go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        txnList.setModel(this.txnListModel);
        jScrollPane1.setViewportView(txnList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameField)
                    .addComponent(jLabel3)
                    .addComponent(timeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        int epoch = epochs[timeSelectModel.getIndexOf(timeSelectModel.getSelectedItem())];
        Logger.info("Loading txn for user in " + epoch + " hours");
        Result<Report> r = Report.getReport(user, epoch);
        if (!r.success) {
            AlertUI.error(r.msg);
            return;
        }
        Report report = r.unwrap();
        Logger.info("Report loaded");
        this.txnListModel = new DefaultListModel<>();
        txnListModel.addElement(header);
        report.getTransactionList().forEach(txn -> {
            txnListModel.addElement(txn.toString());
        });
        txnList.setModel(txnListModel);
    }//GEN-LAST:event_goButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> txnList;
    private javax.swing.JLabel usernameField;
    // End of variables declaration//GEN-END:variables
}
