/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankUI.components.interest;

import bankBackend.Config;
import bankBackend.entity.account.Account;
import bankBackend.entity.enums.RateType;
import bankBackend.service.SvcMgr;
import bankUI.utils.UIContextMgr;

import javax.swing.table.DefaultTableModel;

/**
 * @author NathanY
 */
public class LoanUI extends javax.swing.JFrame {

    private String[] header = {"id", "amount", "payback amount", "rate", "start date", "end date", "calculate type", "collat", "description"};
    private DefaultTableModel loanModel = new DefaultTableModel();
    /**
     * Creates new form SavingUI
     */
    private int rate = 0;
    private String uname = "";

    public LoanUI() {
        initComponents();
    }

    public void loadCtx() {
        rate = SvcMgr.getInterestRateService().getGlobalInterestRate(RateType.Loan);
        this.rateLabel.setText(rate + "%");
        uname = SvcMgr.getUserService().getUsernameByAccountId(UIContextMgr.getAccount(this).getId());
        this.unameLabel.setText(uname);
        this.loanModel = new DefaultTableModel();
        loanModel.setColumnIdentifiers(header);
        SvcMgr.getInterestRateService().getInterestRate(UIContextMgr.getAccount(this).getId(), RateType.Loan).forEach(ir -> {
            loanModel.addRow(new Object[]{ir.getId(), ir.getInitValue(), ir.getPaybackValue(),
                    ir.getRate() + "%", ir.getStartEpoch() / Config.HOUR_PER_DAY, ir.getEndEpoch() / Config.HOUR_PER_DAY,
                    ir.getMethod(), ir.getCollat_user_id(), ir.getDescription()});
        });
        this.historyTable.setModel(loanModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        unameLabel = new javax.swing.JLabel();
        newLoanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        unlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Loan history of User");

        newLoanBtn.setText("Start a new loan");
        newLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLoanBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Today's interest rate:");

        rateLabel.setText("" + this.rate + "%");

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                        "id", "amount", "payback amount", "rate", "start date", "end date", "calculate type", "collat", "description"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(historyTable);

        unlabel.setText(this.uname);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(unlabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(unameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addGap(1, 1, 1)
                                                .addComponent(rateLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newLoanBtn)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(unameLabel)
                                        .addComponent(newLoanBtn)
                                        .addComponent(jLabel3)
                                        .addComponent(rateLabel)
                                        .addComponent(unlabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLoanBtnActionPerformed
        // TODO add your handling code here:

        LoanApplicationUI laui = new LoanApplicationUI();
        Account acc = UIContextMgr.getAccount(this);
        UIContextMgr.setAccount(laui, acc);
        laui.setVisible(true);
    }//GEN-LAST:event_newLoanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newLoanBtn;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JLabel unlabel;
    // End of variables declaration//GEN-END:variables
}
